export const ADMIN_SET_PRODUCT = 'ADMIN_SET_PRODUCT';
export const ADMIN_REMOVE_PRODUCT = 'ADMIN_REMOVE_PRODUCT';
export const ADMIN_ADD_PRODUCT = 'ADMIN_ADD_PRODUCT';
export const ADMIN_SET_ORDERS = 'ADMIN_SET_ORDERS';
export const ADMIN_CHANGE_ORDER_STATUS = 'ADMIN_CHANGE_ORDER_STATUS';
export const ADMIN_CANCELL_ORDER = 'ADMIN_CANCELL_ORDER';